---
- hosts: mywebserver
  become: yes
  tasks:
    - name: Ensure Java is installed
      apt:
        name: "{{myjavapackonubuntu}}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
    
    
