---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install webserver on ubnutu nodes ( $ sudo apt-get install apcche2 )
    apt: 
      name: "{{mywebpackonubuntu}}" 
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to start webserver  on ubuntu nodes ($ sudo  service apache2 start)
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family=="Debian" 

  - name: i want to install webserver on redhat node 
    dnf:
       name: "{{mywebpackonredhat}}"
       state: present
    when: ansible_os_family =="RedHat"

  - name: i want to start mywebserver  on RedHat 
    service:
       name: "{{mywebpackonredhat}}"
       state: started
    when: ansible_os_family =="RedHat"
